folder_to_search : "/home/tobias/Selbstständig/Rechnungen/Selbständig/2020/Bahnrechnungen"
invoice_dir : "/home/tobias/Selbstständig/Rechnungen/Selbständig/2020/Bahnrechnungen_backup"
cost_sheet : "/home/tobias/Selbstständig/Rechnungen/Selbständig/2020/Bahnrechnungen/bills_eur.ods"
